# Generated by Django 3.0.4 on 2020-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200318_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
