# Generated by Django 3.0.4 on 2020-03-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200323_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
